/* tslint:disable */
/* eslint-disable */
/**
 * eCommerce API
 * API for eCommerce app that displays a list of products and product details.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Unique identifier of the product
     * @type {string}
     * @memberof Product
     */
    'id': string;
    /**
     * Title of the product
     * @type {string}
     * @memberof Product
     */
    'title': string;
    /**
     * Category of the product
     * @type {string}
     * @memberof Product
     */
    'category': string;
    /**
     * URL of the product image
     * @type {string}
     * @memberof Product
     */
    'image': string;
    /**
     * Total number of items sold
     * @type {number}
     * @memberof Product
     */
    'sold': number;
    /**
     * Price of the product
     * @type {number}
     * @memberof Product
     */
    'price': number;
    /**
     * Total sales value in dollars
     * @type {number}
     * @memberof Product
     */
    'sales_value': number;
}
/**
 * 
 * @export
 * @interface ProductDetails
 */
export interface ProductDetails {
    /**
     * Unique identifier of the product
     * @type {string}
     * @memberof ProductDetails
     */
    'id': string;
    /**
     * Title of the product
     * @type {string}
     * @memberof ProductDetails
     */
    'title': string;
    /**
     * Detailed description of the product
     * @type {string}
     * @memberof ProductDetails
     */
    'description': string;
    /**
     * Available size(s) for the product
     * @type {string}
     * @memberof ProductDetails
     */
    'size'?: string;
    /**
     * Name of the company that manufactures the product
     * @type {string}
     * @memberof ProductDetails
     */
    'company_name': string;
    /**
     * Tags related to the product for categorization and filtering
     * @type {Array<string>}
     * @memberof ProductDetails
     */
    'tags'?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of 10 products, including details like image, title, category, sold, price, and sales value.
         * @summary Get a list of products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns details for a specific product based on its ID, including title, description, size, company name, and tags.
         * @summary Get product details
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsProductIdGet: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('productsProductIdGet', 'productId', productId)
            const localVarPath = `/products/{productId}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of 10 products, including details like image, title, category, sold, price, and sales value.
         * @summary Get a list of products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Product>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.productsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns details for a specific product based on its ID, including title, description, size, company name, and tags.
         * @summary Get product details
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsProductIdGet(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsProductIdGet(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.productsProductIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Returns a list of 10 products, including details like image, title, category, sold, price, and sales value.
         * @summary Get a list of products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Product>> {
            return localVarFp.productsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns details for a specific product based on its ID, including title, description, size, company name, and tags.
         * @summary Get product details
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsProductIdGet(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<ProductDetails> {
            return localVarFp.productsProductIdGet(productId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Returns a list of 10 products, including details like image, title, category, sold, price, and sales value.
     * @summary Get a list of products
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public productsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).productsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns details for a specific product based on its ID, including title, description, size, company name, and tags.
     * @summary Get product details
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public productsProductIdGet(productId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).productsProductIdGet(productId, options).then((request) => request(this.axios, this.basePath));
    }
}



