/* tslint:disable */
/* eslint-disable */
/**
 * eCommerce API
 * API for eCommerce app that displays a list of products and product details.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDetails
 */
export interface ProductDetails {
    /**
     * Unique identifier of the product
     * @type {string}
     * @memberof ProductDetails
     */
    id: string;
    /**
     * Title of the product
     * @type {string}
     * @memberof ProductDetails
     */
    title: string;
    /**
     * Detailed description of the product
     * @type {string}
     * @memberof ProductDetails
     */
    description: string;
    /**
     * Available size(s) for the product
     * @type {string}
     * @memberof ProductDetails
     */
    size?: string;
    /**
     * Name of the company that manufactures the product
     * @type {string}
     * @memberof ProductDetails
     */
    companyName: string;
    /**
     * Tags related to the product for categorization and filtering
     * @type {Array<string>}
     * @memberof ProductDetails
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the ProductDetails interface.
 */
export function instanceOfProductDetails(value: object): value is ProductDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    return true;
}

export function ProductDetailsFromJSON(json: any): ProductDetails {
    return ProductDetailsFromJSONTyped(json, false);
}

export function ProductDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'size': json['size'] == null ? undefined : json['size'],
        'companyName': json['company_name'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function ProductDetailsToJSON(value?: ProductDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'size': value['size'],
        'company_name': value['companyName'],
        'tags': value['tags'],
    };
}

